language: python
matrix:
    include:
        - python: "3.5"
          env: TOXENV=py35
        - python: "3.6"
          env: TOXENV=py36
        - python: "3.7"
          env: TOXENV=py37

install:
    - pip install -U pip setuptools
    - pip install -U tox coveralls coverage

before_script:
  - export TZ=US/Eastern

script:
    - tox

after_success:
    - coverage combine
    - coveralls

cache:
  pip: true
  directories:
    - eggs/
