dist: focal
language: python
python:
    - 3.5
    - 3.6
    - 3.7

install:
    - pip install tox-travis

before_script:
  - export TZ=US/Eastern

script:
    - tox

after_success:
    - coverage combine
    - coveralls

cache:
  pip: true
  directories:
    - eggs/
